### PR TITLE
RFA: REP-I0004: Add vendor specific ranges for Epson & Stäubli [ under-review ]

### PR DESCRIPTION
**Pull request by gavanderhoorn**
**This RFA is under review**.

As per subject.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Revision history will be updated if/when this PR is accepted.

**Comment by shaun-edwards** [comment]
+1...thanks for updating.

**Comment by JeremyZoss** [comment]
+1 from me.

Why don't we just assign all of 1000-2999 to "Vendor-Specific", even if some of that range is currently unassigned to specific vendors?  It seems unlikely that we'll throw general-purpose messages in the middle of that range, when we have all of 3000-65000 (and the upper block) available.

Other random inconsistencies that could be cleared up:
  - There is no indication of the plan for range 2100-2999.
  - Most of the ranges start at xx00 and end at xx99.  The breakpoint at 65000 is different.  What if we just allow 65000 to be freely assignable?

**Comment by gavanderhoorn** [comment]
@JeremyZoss wrote:
> Why don't we just assign all of 1000-2999 to "Vendor-Specific", even if some of that range is currently unassigned to specific vendors? It seems unlikely that we'll throw general-purpose messages in the middle of that range, when we have all of 3000-65000 (and the upper block) available.

The fragmentation is the result of reducing the vendor specific ranges from a 1000 IDs to 100 each. It was unfortunate, but Motoman (the second vendor, after SwRI), already was assigned `2000` to `3000`.

What we can do is make the `1000` to `3000` range *Vendor Specific* in the first table (under *Standard Messages*), and then make the currently unassigned ranges in that range *Reserved for future use* in the second table. That would reduce the fragmentation of the first table, and still make it clear that the document is not missing registrations for the parts of the *Vendor Specific* range that don't seem to have been assigned in the table under *Vendor Specific Ranges*.

>  - There is no indication of the plan for range 2100-2999.

<del>Not sure I follow: do you feel we should document what the intended use of is those IDs?</del> O, now I see. There is indeed a gap between `2099` and `3000`. Again a result of the shuffle when we shortened the vendor ranges.

> Most of the ranges start at xx00 and end at xx99. The breakpoint at 65000 is different. What if we just allow 65000 to be freely assignable?

Ha, yeah. Agreed.

I'll make the changes and include them in this RFA.

**Comment by gavanderhoorn** [comment]
Updated the RFA.

Thanks for the comments @JeremyZoss, and the thorough review of the document.

**Comment by gavanderhoorn** [comment]
I'm closing the vote. Summary:

```
 +1: 2
  0: 0
 -1: 0
```

Which means the RFA has been accepted, and REP-I0004 will be updated to include assignments for *vendor specific* ranges for both Epson and Mitsubishi.

**Comment by gavanderhoorn** [comment]
Thanks for taking the time to vote @shaun-edwards and @JeremyZoss.

**Pull request merged**
