### PR TITLE
Elfin robot range assigment

### PR DESCRIPTION
**Pull request by calvama**

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Thanks for the PR.

Could you clarify two things for me please:

 1. have you read the [*Application Procedure*](https://github.com/ros-industrial/rep/blob/4a82b107e591a890595d371517285c8ae4ed0234/rep-I0004.rst#application-procedure) section of  REP-I4? It describes the procedure to follow when considering requesting new ranges of message identifiers. A PR like this one would be the end of that procedure.
 1. are you (intending to) use(ing) `simple_message` and `industrial_robot_client`? If yes: please clarify why. If no: in that case there is no need to reserve a range of message identifiers, as those are only used with the Simple Message protocol. They are not used in any ROS API.

For new robots I would not recommend using Simple Message.

**Comment by gavanderhoorn** [comment]
Please note that REP-I4 directs application requests to the "ROS-Industrial mailing list".

This no longer exists.

RFAs should be sent to the [ROS-Industrial category](https://discourse.ros.org/c/ros-industrial) on ROS Discourse.

**Comment by calvama** [comment]
> Thanks for the PR.
> 
> Could you clarify two things for me please:
> 
> 1. have you read the [_Application Procedure_](https://github.com/ros-industrial/rep/blob/4a82b107e591a890595d371517285c8ae4ed0234/rep-I0004.rst#application-procedure) section of  REP-I4? It describes the procedure to follow when considering requesting new ranges of message identifiers. A PR like this one would be the end of that procedure.
> 2. are you (intending to) use(ing) `simple_message` and `industrial_robot_client`? If yes: please clarify why. If no: in that case there is no need to reserve a range of message identifiers, as those are only used with the Simple Message protocol. They are not used in any ROS API.
> 
> For new robots I would not recommend using Simple Message.

1. Ups, no sorry.
2. Yes, we are intending to use `simple_message` and `industrial_robot_client` as recommended here: http://wiki.ros.org/Industrial/Industrial_Robot_Driver_Spec. Specifically: "New robot implementations are encouraged to consider using this client".

Why do you not recommend using Simple Message?

**Comment by gavanderhoorn** [comment]
> Why do you not recommend using Simple Message?

In short: because it's a very limited protocol and modern robot controllers typically have much better external motion interfaces available (such as Ethercat, CAN(open), a custom UDP or TCP based protocol, etc). Those are almost always more performant, supported by the manufacturer, real-time capable/safe (especially UDP based protocols, or real-time safe fieldbuses such as Ethercat) and can use existing tooling, libraries and experience.

See [ROS Answers/335913](https://answers.ros.org/question/335913) for a somewhat longer recent discussion about this.

>     2\. Yes, we are intending to use `simple_message` and `industrial_robot_client` as recommended here: http://wiki.ros.org/Industrial/Industrial_Robot_Driver_Spec. Specifically: "New robot implementations are encouraged to consider using this client".

Please note: that particular section is very old (admittedly this is not visible to you) and "new drivers" refers to drivers created *after* `industrial_robot_client` was just introduced. Up till then (ie: when that section was written), all robot driver (supported in ROS-Industrial) used different, custom protocols. Hence the recommendation to move away from that and implement new ones using the (then) "new" Simple Message and Industrial Robot Client.

---

Summarising: if you have the option, I would recommend to not use Simple Message.

**Comment by calvama** [comment]
Ok, we won't use Simple Messagge. Can we consider the rest of Driver Spec page up to date? (topics and services to be implementes/remapped)

**Comment by gavanderhoorn** [comment]
> Ok, we won't use Simple Messagge.

Then I'll close this PR.

> Can we consider the rest of Driver Spec page up to date? (topics and services to be implementes/remapped)

Yes, I would say so. SOP for me is to just implement "regular" ROS APIs for drivers and then add remaps if/when needed.

For support packages, I would suggest to take a look at the `ros-industrial/fanuc` repository.

You may also want to read [Coordinate Frames for Serial Industrial Manipulators](http://gavanderhoorn.github.io/rep/rep-0199.html). It's not been accepted yet (submission planned), but it documents best practices wrt frame names, locations and semantics for industrial robot models in ROS.

**Comment by gavanderhoorn** [comment]
Closing as based on the discussion, Simple Message will not be used for the driver.

**Pull request closed without merging**
