### PR TITLE
assigned-ids: add vendor ranges for robot mfgs.

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

I've updated the vendor ranges with all the currently supported robot platforms.

Assignments are (sort of) in chronological order wrt when ROS-I drivers were released / created (suggestion by @dpsolomon).

And I've treated the UR as a 'Simple Message platform', even though it currently doesn't use the protocol.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Friendly ping.

**Comment by shaun-edwards** [comment]
+1

**Comment by thiagodefreitas** [comment]
+1

**Comment by dpsolomon** [comment]
+1

**Pull request merged**
