### PR TITLE
REP on naming ABB resources

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

Refer to ros-industrial/abb#75 for context.

Link to [rendered version](https://github.com/gavanderhoorn/rep-ros-i/blob/abb_naming/rep-ixxxx.rst).

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
@Samsagax

**Comment by gavanderhoorn** [comment]
Question: should there be a section documenting some alternative templates that have been discussed but did not make it?

**Comment by Samsagax** [comment]
@gavanderhoorn I've read it. Itlooks fine to me. regarding your last question, it doesn't seem necessary, we should link to the GH discussion instead.

**Comment by gavanderhoorn** [comment]
Thanks for your comments.

We could link to the discussion, but some REPs include an "design alternatives" section directly in the document itself. That way future readers would not have to refer to external resources (that might disappear).

I'm not opposed to linking to the discussion for that though. ros-industrial/abb#75 is already linked in it.

**Comment by gavanderhoorn** [comment]
🛎 @shaun-edwards @Levi-Armstrong ;)

**Comment by gavanderhoorn** [comment]
After some additional `+1`s, the REP should get an *Active* state and should be assigned a nr.

I think 7 is free.

**Comment by gavanderhoorn** [comment]
@JeremyZoss wrote:
> The inclusion of payload is messy (file replication with trivial differences), but maintains compliance with ABB's naming conventions, which is probably a net positive.

yes, payload was a difficult choice. We discussed this in ros-industrial/abb#75. Reason I included it is indeed because we stick to ABBs conventions.

And not described in this document, but to avoid unnecessary duplication two variants with the same reach but different payload (like the 2400-12/1.55 and -20/1.55, see the [readme](https://github.com/ros-industrial/abb/blob/0e9fb652e577e10d9c987e43c706b8beef7947f1/abb_irb2400_support/readme.md)) can just use each others urdfs/meshes (ie: use the `abb_irb2400_12_155` model for the 20Kg variant). At least until MoveIt or other planners become payload-aware.

> My (weak) preference would have been to round payload to the nearest 1kg, but the current 0-prefix is also intuitive. Similarly, I would have preferred to leave off payload/reach except where required to distinguish between current variants. But I can see how the current approach is more future-proof.

We thought about this, but decided against it as it would mean that we'd be less consistent: for example for an `abb_irb6600_225` (I just made this up) is `225` the reach or the payload? This might be clear for someone who knows the series well, but I want things to be clear for all users.

I agree that shorter names are always preferable, but in this case I felt that avoiding potential ambiguity was more important.

> Consider adding examples of typical naming/layout of artefacts (e.g. _support packages). It's non-obvious, even though I'm sure your description is complete. Levi's example was helpful in this regard.

Which example are you referring to here?

> Also, some guidance on expectations for how to minimize duplication (e.g. in xacros, launch files, etc.) would be welcome. This might be more suited as a wiki page, though, since it tends to be cross-platform.

Yes, so initially I wanted to add them to this REP, but thinking about it such rules / guidelines wouldn't be ABB specific at all. So I did not include them, with the idea that a REP on artefact naming and support package layout would be more efficient as it could be 'shared' by all Mfgs we support.

That REP could then point to this one (and others for the different Mfgs) for ABB-specific rules on naming.

Perhaps I should make it clearer that this REP really is only about converting product names. I thought the title would convey that already :).

> Sorry for the late comments. Overall, looks good to me.

No problem. Thanks for the review.

I think I will add that *Design Alternatives* section after all, which would address exactly the points that you raised.

**Comment by JeremyZoss** [comment]
I was referring to Levi's [comment](https://github.com/ros-industrial/abb/issues/75#issuecomment-276082020) on Issue #[75](https://github.com/ros-industrial/abb/issues/75).

**Comment by gavanderhoorn** [comment]
Btw: quite some time ago I started on a REP documenting ROS-I support pkg layout: [Layout of ROS Industrial manufacturer support repositories](https://github.com/gavanderhoorn/rep/blob/repository_layout/rep-xxxx.rst). That was (and still is) intended to contain the "examples of typical naming/layout of artefacts".

**Comment by Levi-Armstrong** [comment]
:+1:

**Comment by shaun-edwards** [comment]
Don't wait on me guys...pretty overwhelmed these days.

**Comment by gavanderhoorn** [comment]
I've added a section that discusses the "ignore payload" alternative.

**Comment by gavanderhoorn** [comment]
I've made this REP `7` and synced creation and posting dates.

If I don't receive any more comments by 8pm CET, I'll mark the REP as *active* and merge it.

**Comment by gavanderhoorn** [comment]
Thanks for all the input @Levi-Armstrong, @Samsagax, @shaun-edwards and @JeremyZoss.

Appreciated 💯

**Pull request merged**
