### PR TITLE
Fix misc rst markup issues in REPs 1, 2 and 3

### PR DESCRIPTION
**Pull request by gavanderhoorn**
Noticed these while testing out `doc8` (#21).

No content changes, just rst markup.

Remaining issue that `doc8` complains about is `D001 Line too long`, which is caused by the fact that none of the REPs wrap lines.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
A diff ignoring whitespace changes: [link](https://github.com/ros-industrial/rep/compare/fix_rst_errors?w=1).

**Comment by gavanderhoorn** [comment]
@robinsonmm: do you think you could review this PR?

**Comment by gavanderhoorn** [comment]
Thanks 👍 

(reviews are per PR, not per file btw, so a single approval wouldn't been enough :))

**Comment by robinsonmm** [comment]
Sorry, yeah I thought, but was being thorough.

**Comment by gavanderhoorn** [comment]
Well they've all been vetted now :)

**Pull request merged**
